#!/bin/bash
sbatch --nodes=1 -o nodes_1.out job_lumi.sh "$1"
sbatch --nodes=2 -o nodes_2.out job_lumi.sh "$1"
sbatch --nodes=4 -o nodes_4.out job_lumi.sh "$1"
sbatch --nodes=8 -o nodes_8.out job_lumi.sh "$1"
sbatch --nodes=16 -o nodes_16.out job_lumi.sh "$1"
sbatch --nodes=32 -o nodes_32.out job_lumi.sh "$1"
sbatch --nodes=64 -o nodes_64.out job_lumi.sh "$1"
sbatch --nodes=128 -o nodes_128.out job_lumi.sh "$1"
sbatch --nodes=256 -o nodes_256.out job_lumi.sh "$1"
